import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";

import "./globals.css";

import BaseLayout from "@/layouts/Base";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = async ({ children }) => (
  <html lang="en">
    <body className="antialiased">
      <BaseLayout>{children}</BaseLayout>
    </body>
  </html>
);

export default RootLayout;
